name: Auto Update Sales Dataset

on:
  schedule:
    - cron: '0 0 * * 1'   # Понеделник 00:00 UTC
  workflow_dispatch:       # Рачно стартување

jobs:
  run-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run update script
      run: python update.py

    - name: Commit and push updated CSV
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add sales.csv
        git commit -m "Weekly dataset update"
        git push
